<?php
    session_start();
    if (!isset($_SESSION['esta_logado']) OR $_SESSION['esta_logado'] == false){
        header('Location: login.php');

}
    require 'controlador_agenda.php';

    if (isset($_GET['buscar']) && !empty($_GET['buscar'])) {
    	$meusContatos = buscar($_GET['buscar']);
    }else{
    	$meusContatos = getContatos();
    }

?>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Agenda</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<style type="text/css">
		#sair{
			text-align: right;
		}
	</style>
</head>
<body>

	
	<div class="container" style="margin-top: 30px;">

		<h3>Agenda de Contatinhos</h3>
		<br />
		
		<!-- CADASTRO-->
		<div class="row">
			<div class="col-md-12">
				<form class="form-inline" method="post" action="controlador_agenda.php?acao=cadastro">
				  
				  <!--nome-->
				  <div class="form-group">
				    <label for="nome">Nome </label>
				    <input name="nome" type="text" class="form-control" id="nome">
				  </div>
				  
				  <!--email-->
				  <div class="form-group">
				    <label for="email">Email</label>
				    <input name="email" type="e-mail" class="form-control" id="email">
				  </div>

				  <!--telefone-->
				  <div class="form-group">
				    <label for="telefone">Telefone</label>
				    <input name="telefone" type="text" class="form-control" id="telefone">
				  </div>
				  
				  <button type="submit" class="btn btn-default">Cadastrar</button><br><br><br>

                    <!--busca-->
                    <form method="post" action="controlador_agenda.php?acao=buscar">
                        <label for="buscar">Busca</label>
                        <input name="buscar" type="text" class="btn btn-default" id="buscar">
                        <button type="submit" class="btn btn-default">Buscar</button>
                    </form>
				
				</form>
			</div>
            <br><br><br>

		</div>
        <br><br><br>
        <div id="sair" class="row">
            <div class="col-md-12">
            <a href="verifica_usuario.php?acao=sair">Sair</a>
            </div>
        </div>

		<br />
		
		<!--CONTATOS-->
		<div class="row">
			<div class="col-md-12">

				<!-- Conteúdo -->
				<table class="table"> 
					<thead> 
						<tr> 
							<th></th>
							<th>Nome</th> 
							<th>Email</th> 
							<th>Telefone</th>
                            <th>Ações</th>
						</tr> 
					</thead> 
					<tbody> 
						<!-- repetir -->
                        <?php
                            foreach ($meusContatos as $contato):
                        ?>
						<tr> 
							<td><?= $contato['id'] ?></td>
							<td><?= $contato['nome'] ?></td>
							<td><?= $contato['email'] ?></td>
							<td><?= $contato['telefone'] ?></td>
							<td>
                                <a href="editar.php?id=<?=$contato['id']?>">Editar</a>
                                <a href="controlador_agenda.php?acao=excluir&id=<?= $contato['id'] ?>">Excluir</a>
                            </td>
						</tr>
                        <?php
                            endforeach;
                        ?>
					</tbody> 
				</table>
			</div>
		</div>
	</div>
</body>
</html>
